name: Browser Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm i

      - name: Install Playwright browsers and OS deps
        run: |
          npx playwright install-deps
          npx playwright install

      - name: Run all browser tests
        run: |
          npm run test:browser:all

